In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from xgboost import XGBClassifier
from sklearn.calibration import CalibratedClassifierCV
import pandas as pd

from heart_disease.data.ingestion import load_file
from heart_disease.data.splitting import split_data
import heart_disease.models.train as t
from heart_disease.features.preprocessing import (
    create_training_pipeline,
    create_categorical_pipeline,
    create_numeric_pipeline,
    create_preprocessor,
)
from heart_disease.config import (
    INTERIM_DATA_DIR,
    RANDOM_STATE,
    TARGET_COLUMN,
    FEATURES,
    MODEL_DIR,
    ExperimentConfig,
)
from heart_disease.models.tracking import start_experiment

# Import and Split Data

In [2]:
df = load_file(INTERIM_DATA_DIR / "cleaned_dataset.csv")
df.head()

   age     sex    dataset  ...   ca               thal  target
0   63    Male  Cleveland  ...  0.0       fixed defect       0
1   67    Male  Cleveland  ...  3.0             normal       1
2   67    Male  Cleveland  ...  2.0  reversable defect       1
3   37    Male  Cleveland  ...  0.0             normal       0
4   41  Female  Cleveland  ...  0.0             normal       0

[5 rows x 15 columns]

In [3]:
X_train, X_test, y_train, y_test = split_data(df, TARGET_COLUMN, FEATURES)
X_test.to_parquet(INTERIM_DATA_DIR / "X_test.parquet", index=False)
y_test.to_frame("target").to_parquet(INTERIM_DATA_DIR / "y_test.parquet", index=False)

2026-09-15 19:36:13,059 | INFO | heart_disease.data.splitting | Created with shape of X_train: (736, 13), X_test: (184, 13), y_train: (736,), y_test: (184,)

# Build Baseline Model

In [4]:
logistic_regression = create_training_pipeline(
    LogisticRegression(random_state=RANDOM_STATE, max_iter=1000)
)

t.cross_validate_model(
    logistic_regression, X_train, y_train, t.TrainingConfig(ExperimentConfig())
)

2026-09-15 19:36:13,189 | INFO | heart_disease.models.train | Starting cross validation for LogisticRegression model with cv: StratifiedKFold(n_splits=5, random_state=42, shuffle=True) and scoring: f1
2026-09-15 19:36:14,616 | INFO | heart_disease.models.train | Finishing cross validation with scores: CV F1: 0.832 ± 0.011

     fold 1    fold 2    fold 3    fold 4    fold 5      mean       std
0  0.816568  0.823529  0.835443  0.836364  0.849673  0.832315  0.011425

# Evaluate Dataset Based On Model Performance

## Evaluate maximum missing data allowed in each observation

Each observation contains fourteen features that may provide useful predictive information.
However, some observation have more than half of their features missing, potentially indicating poor data quality. 
Therefore, we evaluate different threshold for removing observations based on their proportion of missing values using cross-validation. 
The selected threshold must satisfy two constraint: the proportion of discarded observations must not exceed `ten percent` of the dataset, and the refined dataset must have less than one percent difference in target mean with the original dataset.

In [5]:
results = []

for num in range(6, 14):
    initial_rows = X_train.shape[0]
    temporary_df = X_train.copy()
    temporary_df[TARGET_COLUMN] = y_train.copy()
    temporary_df = temporary_df.dropna(thresh=num)

    X = temporary_df[FEATURES]
    y = temporary_df[TARGET_COLUMN]

    scores = t.cross_validate_model(
        logistic_regression, X, y, t.TrainingConfig(ExperimentConfig())
    )

    scores["threshold"] = num
    scores["total_rows"] = X.shape[0]
    scores["%_rows_deleted"] = (initial_rows - X.shape[0]) / initial_rows * 100
    scores["total_rows x mean"] = scores["total_rows"] * scores["mean"]
    scores["target_mean"] = y.mean()
    results.append(scores)

results = pd.concat(results)
results = results.sort_values("total_rows x mean", ascending=False).set_index(
    "threshold"
)
results

2026-09-15 19:36:14,784 | INFO | heart_disease.models.train | Starting cross validation for LogisticRegression model with cv: StratifiedKFold(n_splits=5, random_state=42, shuffle=True) and scoring: f1

2026-09-15 19:36:15,860 | INFO | heart_disease.models.train | Finishing cross validation with scores: CV F1: 0.832 ± 0.011
2026-09-15 19:36:15,873 | INFO | heart_disease.models.train | Starting cross validation for LogisticRegression model with cv: StratifiedKFold(n_splits=5, random_state=42, shuffle=True) and scoring: f1
2026-09-15 19:36:17,188 | INFO | heart_disease.models.train | Finishing cross validation with scores: CV F1: 0.844 ± 0.019
2026-09-15 19:36:17,205 | INFO | heart_disease.models.train | Starting cross validation for LogisticRegression model with cv: StratifiedKFold(n_splits=5, random_state=42, shuffle=True) and scoring: f1
2026-09-15 19:36:18,371 | INFO | heart_disease.models.train | Finishing cross validation with scores: CV F1: 0.852 ± 0.034
2026-09-15 19:36:18,384 | INFO | heart_disease.models.train | Starting cross validation for LogisticRegression model with cv: StratifiedKFold(n_splits=5, random_state=42, shuffle=True) and scoring: f1
2026-09-15 19:36:20,712 | INFO | heart_disease.models.train | Finishing cross validation with scores: CV F1: 0.853 ± 0.024
2026-09-15 19:36:20,742 | INFO | heart_disease.models.train | Starting cross validation for LogisticRegression model with cv: StratifiedKFold(n_splits=5, random_state=42, shuffle=True) and scoring: f1
2026-09-15 19:36:21,592 | INFO | heart_disease.models.train | Finishing cross validation with scores: CV F1: 0.842 ± 0.020
2026-09-15 19:36:21,615 | INFO | heart_disease.models.train | Starting cross validation for LogisticRegression model with cv: StratifiedKFold(n_splits=5, random_state=42, shuffle=True) and scoring: f1
2026-09-15 19:36:22,497 | INFO | heart_disease.models.train | Finishing cross validation with scores: CV F1: 0.868 ± 0.024
2026-09-15 19:36:22,512 | INFO | heart_disease.models.train | Starting cross validation for LogisticRegression model with cv: StratifiedKFold(n_splits=5, random_state=42, shuffle=True) and scoring: f1
2026-09-15 19:36:23,768 | INFO | heart_disease.models.train | Finishing cross validation with scores: CV F1: 0.866 ± 0.015
2026-09-15 19:36:23,782 | INFO | heart_disease.models.train | Starting cross validation for LogisticRegression model with cv: StratifiedKFold(n_splits=5, random_state=42, shuffle=True) and scoring: f1
2026-09-15 19:36:24,499 | INFO | heart_disease.models.train | Finishing cross validation with scores: CV F1: 0.831 ± 0.026

             fold 1    fold 2  ...  total_rows x mean  target_mean
threshold                      ...
7          0.817073  0.857143  ...         613.615494     0.551582
6          0.816568  0.823529  ...         612.584184     0.552989
8          0.800000  0.872483  ...         588.200132     0.546377
9          0.851351  0.858974  ...         586.914157     0.545058
10         0.870130  0.829630  ...         546.339784     0.546995
11         0.850000  0.877193  ...         411.320489     0.613924
12         0.869565  0.857143  ...         347.164008     0.586035
13         0.808511  0.800000  ...         217.653844     0.473282

[8 rows x 11 columns]

Based on the results of testing the multiple threshold above, a threshold of twelve, which retains only rows with at least twelve non-missing features, results in the highest F1-score. However, this threshold has tow major drawbacks: it discards thirty-six percent of the training data and results in a substantial difference in the target mean compared with the original dataset.
Three threshold satisfy our previously defined constraints: seven, eight, and nine while six represent the original dataset. Amongthese feasible threshold, we choose a threshold of nine because it achieves a hogher F1-score while stll satisfying both constrains.

In [6]:
len(X_train.columns)

13

The threshold selection process is based on `X_train` with `y_train` and depends on the total number of features. Therefore, the threshold values should be adjusted according to the dimensionality of the dataset.

In [7]:
mask = X_train.notna().sum(axis=1) >= 8

X_train = X_train.loc[mask]
y_train = y_train.loc[mask]

In [8]:
X_train.shape

(688, 13)

In [9]:
strategies = {
    "indicators_both": create_preprocessor(
        numeric_pipeline=create_numeric_pipeline(add_indicator=True),
        categorical_pipeline=create_categorical_pipeline(add_indicator=True),
    ),
    "indicators_numeric": create_preprocessor(
        numeric_pipeline=create_numeric_pipeline(add_indicator=True),
        categorical_pipeline=create_categorical_pipeline(add_indicator=False),
    ),
    "indicators_categorical": create_preprocessor(
        numeric_pipeline=create_numeric_pipeline(add_indicator=False),
        categorical_pipeline=create_categorical_pipeline(add_indicator=True),
    ),
    "indicators_none": create_preprocessor(
        numeric_pipeline=create_numeric_pipeline(add_indicator=False),
        categorical_pipeline=create_categorical_pipeline(add_indicator=False),
    ),
}

In [10]:
list_of_scores = []

for name, strategy in strategies.items():
    pipeline = create_training_pipeline(
        model=LogisticRegression(random_state=RANDOM_STATE), preprocessor=strategy
    )

    scores = t.cross_validate_model(
        pipeline, X_train, y_train, t.TrainingConfig(ExperimentConfig())
    )

    scores["strategy"] = name
    list_of_scores.append(scores)

list_of_scores = (
    pd.concat(list_of_scores).sort_values("mean", ascending=False).set_index("strategy")
)
list_of_scores

2026-09-15 19:36:24,785 | INFO | heart_disease.models.train | Starting cross validation for LogisticRegression model with cv: StratifiedKFold(n_splits=5, random_state=42, shuffle=True) and scoring: f1
2026-09-15 19:36:26,156 | INFO | heart_disease.models.train | Finishing cross validation with scores: CV F1: 0.853 ± 0.024
2026-09-15 19:36:26,162 | INFO | heart_disease.models.train | Starting cross validation for LogisticRegression model with cv: StratifiedKFold(n_splits=5, random_state=42, shuffle=True) and scoring: f1
2026-09-15 19:36:26,958 | INFO | heart_disease.models.train | Finishing cross validation with scores: CV F1: 0.839 ± 0.018
2026-09-15 19:36:26,961 | INFO | heart_disease.models.train | Starting cross validation for LogisticRegression model with cv: StratifiedKFold(n_splits=5, random_state=42, shuffle=True) and scoring: f1
2026-09-15 19:36:28,267 | INFO | heart_disease.models.train | Finishing cross validation with scores: CV F1: 0.858 ± 0.021
2026-09-15 19:36:28,280 | INFO | heart_disease.models.train | Starting cross validation for LogisticRegression model with cv: StratifiedKFold(n_splits=5, random_state=42, shuffle=True) and scoring: f1
2026-09-15 19:36:29,351 | INFO | heart_disease.models.train | Finishing cross validation with scores: CV F1: 0.829 ± 0.017

                          fold 1    fold 2  ...      mean       std
strategy                                    ...
indicators_categorical  0.845638  0.860759  ...  0.858104  0.020733
indicators_both         0.851351  0.858974  ...  0.853073  0.023627
indicators_numeric      0.832215  0.842767  ...  0.839401  0.018464
indicators_none         0.826667  0.828025  ...  0.828546  0.017189

[4 rows x 7 columns]

In [11]:
selected_preprocessor = strategies["indicators_categorical"]

# Evaluate Different Algorithm

In [12]:
list_of_models = [
    LogisticRegression(random_state=42),
    RandomForestClassifier(random_state=42),
    CalibratedClassifierCV(SVC(), ensemble=False),
    GradientBoostingClassifier(random_state=42),
    KNeighborsClassifier(),
    XGBClassifier(random_state=42),
]

In [13]:
start_experiment()

experiment_config = ExperimentConfig()

training_config = t.TrainingConfig(experiment=experiment_config)

t.model_comparison_cv(
    list_of_models,
    create_training_pipeline,
    X_train,
    y_train,
    training_config,
)

2026-09-15 19:36:32,608 | INFO | heart_disease.models.train | Starting cross-validation for LogisticRegression
2026-09-15 19:37:51,238 | INFO | heart_disease.models.train | Finished LogisticRegression: F1 = 0.8531 ± 0.0236
2026-09-15 19:37:51,244 | INFO | heart_disease.models.train | Starting cross-validation for RandomForestClassifier

🏃 View run LogisticRegression at: http://127.0.0.1:5000/#/experiments/1/runs/7d90ab2c69314b4a82b4bae24acd8efd
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

2026-09-15 19:37:56,145 | INFO | heart_disease.models.train | Finished RandomForestClassifier: F1 = 0.8406 ± 0.0326
2026-09-15 19:37:56,147 | INFO | heart_disease.models.train | Starting cross-validation for CalibratedClassifierCV

🏃 View run RandomForestClassifier at: http://127.0.0.1:5000/#/experiments/1/runs/eebc5dca1f0943b4b4c80428246caf15
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

2026-09-15 19:37:58,340 | INFO | heart_disease.models.train | Finished CalibratedClassifierCV: F1 = 0.8502 ± 0.0217
2026-09-15 19:37:58,341 | INFO | heart_disease.models.train | Starting cross-validation for GradientBoostingClassifier

🏃 View run CalibratedClassifierCV at: http://127.0.0.1:5000/#/experiments/1/runs/06b6812fde6a44539ec644e9c1093c30
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

2026-09-15 19:38:01,454 | INFO | heart_disease.models.train | Finished GradientBoostingClassifier: F1 = 0.8415 ± 0.0144
2026-09-15 19:38:01,457 | INFO | heart_disease.models.train | Starting cross-validation for KNeighborsClassifier

🏃 View run GradientBoostingClassifier at: http://127.0.0.1:5000/#/experiments/1/runs/4bf0eda8cebd4192a0b3c60e0abb1629
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

2026-09-15 19:38:03,114 | INFO | heart_disease.models.train | Finished KNeighborsClassifier: F1 = 0.8330 ± 0.0189
2026-09-15 19:38:03,118 | INFO | heart_disease.models.train | Starting cross-validation for XGBClassifier

🏃 View run KNeighborsClassifier at: http://127.0.0.1:5000/#/experiments/1/runs/bd1493a2bbc64b3e92edf8fcecb58473
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

2026-09-15 19:38:06,090 | INFO | heart_disease.models.train | Finished XGBClassifier: F1 = 0.8378 ± 0.0179

🏃 View run XGBClassifier at: http://127.0.0.1:5000/#/experiments/1/runs/daea41ad9d3840cd88aec0e7d6f76482
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

                        Model  fit_time  Accuracy  ...  Recall      F1  ROC AUC
0          LogisticRegression    0.4764    0.8402  ...  0.8533  0.8531   0.9106
1      CalibratedClassifierCV    0.5100    0.8329  ...  0.8720  0.8502   0.9026
2  GradientBoostingClassifier    1.3450    0.8256  ...  0.8480  0.8415   0.8855
3      RandomForestClassifier    1.4239    0.8257  ...  0.8427  0.8406   0.8879
4               XGBClassifier    0.5295    0.8198  ...  0.8560  0.8378   0.8727
5        KNeighborsClassifier    0.1706    0.8169  ...  0.8400  0.8330   0.8690

[6 rows x 7 columns]

In [14]:
from mlflow import search_runs

search_runs(
    experiment_names=["uci-heart-disease"]
)

                              run_id  ...         tags.mlflow.runName
0   daea41ad9d3840cd88aec0e7d6f76482  ...               XGBClassifier
1   bd1493a2bbc64b3e92edf8fcecb58473  ...        KNeighborsClassifier
2   4bf0eda8cebd4192a0b3c60e0abb1629  ...  GradientBoostingClassifier
3   06b6812fde6a44539ec644e9c1093c30  ...      CalibratedClassifierCV
4   eebc5dca1f0943b4b4c80428246caf15  ...      RandomForestClassifier
5   7d90ab2c69314b4a82b4bae24acd8efd  ...          LogisticRegression
6   4615f58993e34f33ad4b9551f7c6714d  ...               XGBClassifier
7   915dba43be7e479f8d0987656ba5b34b  ...        KNeighborsClassifier
8   e4440d78dea64f1a9de5cade421907e3  ...  GradientBoostingClassifier
9   be8b7943965944b9a0d2fbd4096bb194  ...      CalibratedClassifierCV
10  16ea2bcc522f4c7698895485d6f5a14c  ...      RandomForestClassifier
11  c137f09ec50d4259b7fe33d5434e8343  ...          LogisticRegression
12  8fedf361ba0d4d68a57329f5798276f5  ...               XGBClassifier
13  05f183c2c8bd42f194a348320806c991  ...        KNeighborsClassifier
14  9cfa78d99c4246fe8c61621f6bed4d7c  ...  GradientBoostingClassifier
15  19ebf46aefa3456782726685e1c700ea  ...      CalibratedClassifierCV
16  d355d3bddd69431686a30fa601ca5265  ...      RandomForestClassifier
17  21abb08784d74b00858e880282ee0e1b  ...          LogisticRegression

[18 rows x 120 columns]

# Tune Hyperparameters for Selected Algorithm

In [15]:
param_grid = [
    {
        "classifier__max_iter": [5000],
        "classifier__solver": ["lbfgs"],
        "classifier__C": [0.01, 0.1, 1, 10, 100],
    },
    {
        "classifier__max_iter": [5000],
        "classifier__solver": ["saga"],
        "classifier__C": [0.01, 0.1, 1, 10, 100],
        "classifier__l1_ratio": [0, 0.5, 1],
    },
]

In [16]:
selected_pipeline = create_training_pipeline(
    LogisticRegression(random_state=RANDOM_STATE), selected_preprocessor
)
search = t.grid_search(
    selected_pipeline,
    param_grid,
    X_train,
    y_train,
    t.TrainingConfig(ExperimentConfig()),
)

2026-09-15 19:38:09,035 | INFO | heart_disease.models.train | Starting grid search

2026-09-15 19:38:28,866 | INFO | heart_disease.models.train | Best parameters: {'classifier__C': 1, 'classifier__l1_ratio': 0.5, 'classifier__max_iter': 5000, 'classifier__solver': 'saga'} | Best CV scores: 0.861

In [17]:
search.best_score_

np.float64(0.861117598834755)

In [18]:
selected_model = create_training_pipeline(
    LogisticRegression(
        max_iter=5000, l1_ratio=0.5, C=1, solver="saga", random_state=RANDOM_STATE
    ),
    selected_preprocessor,
)


t.cross_validate_model(
    selected_model, X_train, y_train, t.TrainingConfig(ExperimentConfig())
)

2026-09-15 19:38:28,957 | INFO | heart_disease.models.train | Starting cross validation for LogisticRegression model with cv: StratifiedKFold(n_splits=5, random_state=42, shuffle=True) and scoring: f1
2026-09-15 19:38:30,669 | INFO | heart_disease.models.train | Finishing cross validation with scores: CV F1: 0.861 ± 0.024

     fold 1    fold 2    fold 3    fold 4    fold 5      mean       std
0  0.845638  0.860759  0.826667  0.895105  0.877419  0.861118  0.023864

In [19]:
base_model = create_training_pipeline(LogisticRegression(random_state=RANDOM_STATE))


t.cross_validate_model(
    base_model, X_train, y_train, t.TrainingConfig(ExperimentConfig())
)

2026-09-15 19:38:30,740 | INFO | heart_disease.models.train | Starting cross validation for LogisticRegression model with cv: StratifiedKFold(n_splits=5, random_state=42, shuffle=True) and scoring: f1
2026-09-15 19:38:31,674 | INFO | heart_disease.models.train | Finishing cross validation with scores: CV F1: 0.853 ± 0.024

     fold 1    fold 2    fold 3    fold 4    fold 5      mean       std
0  0.851351  0.858974  0.810811  0.861111  0.883117  0.853073  0.023627

In [20]:
selected_model = t.train_model(selected_model, X_train, y_train)

2026-09-15 19:38:32,238 | INFO | heart_disease.models.train | Training: LogisticRegression with shape of dataframe: (688, 13)

In [21]:
path = MODEL_DIR / "01_selected_model_LR.joblib"
t.save_model(selected_model, path)

2026-09-15 19:38:32,280 | INFO | heart_disease.models.train | Saving LogisticRegression model to /home/irasionize/heart-disease-ml/models/01_selected_model_LR.joblib